# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: black-check
        name: black-check
        entry: black
        language: system
        types: [python]
        args: [--diff, --check]
        pass_filenames: true

      - id: pylint-import-check
        name: pylint-import-check
        entry: pylint
        language: system
        types: [python]
        args: [--disable=all, --enable=unused-import]

      - id: mypy-check
        name: mypy-check
        entry: mypy
        exclude: ^tests/
        language: system
        types: [python]
        args: [--strict, --namespace-packages, --ignore-missing-imports]

      - id: pytest-tests
        name: pytest-tests
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
