name: Publish project to PyPI

on:
  push:

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.9"
      - name: Install 'build'
        run: python3 -m pip install build
      - name: Build project wheel and tarball
        run: python3 -m build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-artifacts
          path: dist/
      - name: Generate release notes
        run: ./generate-notes.sh
        shell: bash
      - name: Upload release notes
        uses: actions/upload-artifact@v4
        with:
          name: notes-artifact
          path: NOTES.md
  publish-to-pypi:
    name: Publish Python distribution to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/laebelmaker
    permissions:
      id-token: write
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: python-package-artifacts
        path: dist/
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
  github-release:
    name: Sign artifacts and create a GitHub Release
    needs:
    - publish-to-pypi
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: python-package-artifacts
        path: dist/
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v1.2.3
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Download NOTES.md
      uses: actions/download-artifact@v4
      with:
        name: notes-artifact
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ github.ref_name }}'
        --repo '${{ github.repository }}'
        --title 'v${{ github.ref_name }}'
        --notes-file NOTES.md
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release upload
        '${{ github.ref_name }}' dist/**
        --repo '${{ github.repository }}'


