name: Python application workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Install laebelmaker
      run: |
        pip install .
    - name: Format with black
      run: |
        black laebelmaker/ --check
    - name: Type check with MyPy
      run: |
        mypy laebelmaker/ --strict --namespace-packages --ignore-missing-imports
    - name: Test with pytest
      run: |
        pytest
    - name: Check for unused imports with pylint
      run: |
        pylint --disable=all --enable=unused-import laebelmaker/
